### ISSUE TITLE
Window too small (Triple Screen 5760x1080)

### ISSUE THREAD

**Issue by Snacko** [ciribob/DCS-SimpleRadio#12]
When SR opens, the window is 1/8 inch wide by 6 inch tall.

Only way to resize is to drag to edge of screen and dock.  Then it makes it way too large, but I can now see the resize grip in the bottom/right corner.

But that does not save after I resize.  When I drag away from the edge it's tiny again.  And it does not save it's size.

**Comment by ciribob** [comment]
Are you sure you don't mean this project? 

https://github.com/ciribob/DCS-SimpleRadioStandalone

In which case please copy over issue.

Theres something odd about triple screen, but only if all the resolutions are the same. I've only got one screen so its going to take me a while to figure out... sorry.

**Comment by Snacko** [comment]
No, it's the Plugin version.  The Plugin shows up in the Teamspeak Plugins and I enable it, and it makes a DCS SimpleRadio menu item.

But now I am trying to uninstall this one and don't see any way to uninstall it?  Do, I just disable it in TS, and then delete the install folder?  I want to try the Standalone verision..  A triple screen friend is using that and said he could resize it after he docked the window.  This version reverts to the small window again after I drag away from the monitor's edge.

**Comment by ciribob** [comment]
Ah gotcha, no worries. Replied on the forums :)

http://forums.eagle.ru/showthread.php?t=146831&page=12
