### ISSUE TITLE
Clean TS3 Window

### ISSUE THREAD

**Issue by ciribob** [ciribob/DCS-SimpleRadio#8]
Clean TS3 window to say not in game after the user leaves DCS

**Comment by splash99** [comment]
I tried with:

if (clientInfoData.unitId==-1) return  "\nStatus: [B]Not In Game[/B]";

before the line:
if (clientInfoData.lastUpdate > 5000ull)

in plugin.cpp. But the effect was having the message Not in Game always in the screen.

**Comment by ciribob** [comment]
Fixed in #11
