### ISSUE TITLE
First radio is the only one that does not allows negative frecuencies

### ISSUE THREAD

**Issue by splash99** [ciribob/DCS-SimpleRadio#9]
I was having a look at GUI's code and I can find an answer. First radios does not allows negative frecuencies. If you go down to zero and press the button below, it goes to 251.000 (this is good in fact). This not happens with the second and third radio.

**Comment by ciribob** [comment]
Thanks! I'll take a look :+1:

**Comment by ciribob** [comment]
I've fixed this and created a new branch: https://github.com/ciribob/DCS-SimpleRadio/commit/89e7bf2d802178cf5f7f23553a0eb9b40cfd6a63

I'll upload a new build for you guys to test and link here shortly.

**Comment by ciribob** [comment]
Also PTT for incockpit is optional and enabled by editing the simpleradio lua by setting: SR.enableInternalPTT = true

**Comment by ciribob** [comment]
Here you go: https://github.com/ciribob/DCS-SimpleRadio/releases/tag/1.4.0

Just ignore the upgrade request.

**Comment by splash99** [comment]
Many thanks!. I'm testing just now. Now we have limits in frecuencies!
A little bug: when you press "Mute No SR" or "Toggle CA Mode", state in changed in TS window but not changes menus.

**Comment by splash99** [comment]
Excellent job Ciribob. I tested all functions and they are working flawlessly. I flew in Su-27, Su-33, Su-25, Su-25T, A-10A, L-39C, Ka-50, MiG-29S.

**Comment by ciribob** [comment]
Thanks for reporting! Try this updated 64bit dll for teamspeak. Should be fixed.
[DCS-SimpleRadio-x64.zip](https://github.com/ciribob/DCS-SimpleRadio/files/181447/DCS-SimpleRadio-x64.zip)

**Comment by ciribob** [comment]
No worries :) I'll do a release later in the week and post on the forums. Thanks for your help testing!

**Comment by splash99** [comment]
thanks. Bug was very very minor! It's working well now.

**Comment by splash99** [comment]
Hi, another bug I detected. If you fly for example in Su-25T and later you fly in F-15C, the second radio shows the last frecuency of Su-25T. Ranges in the GUI for this second radio are the ones of Su-25T and not F-15C. It is not refreshing the parameters for the second radio. I have to test it with the third radio.

Thanks.

**Comment by ciribob** [comment]
Thanks! Tarres sent me a message as well. Bit trickier to solve but fixed now.

Updated here https://github.com/ciribob/DCS-SimpleRadio/releases/tag/1.4.0

**Comment by ciribob** [comment]
You will have to change frequency to "reset" it when you switch aircraft though.

**Comment by ciribob** [comment]
Fixed in #11
